name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: 0 14 * * 0

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Make
        run: make ci
